Add support for checking backup target free space

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Simple backup script
-# 1.0.7 (2016.03.02)
+# 1.0.8 (2016.05.17)
 # writed by vadonka
 
 if [ ! -f /usr/local/etc/simplebackup.conf ]; then
@@ -12,6 +12,9 @@ configured="no"
 
 # Backup files root
 backup_root="/opt/backup"
+
+# Minimum free space on backup target (in kB)
+backup_minfree="524288000"
 
 # Folders to backup, separate folders with space
 folders_to_backup="root etc"
@@ -35,28 +38,28 @@ fi
 source /usr/local/etc/simplebackup.conf
 
 if [[ ${configured} == "no" ]]; then
-    echo "Please setup the configuration file first!"
-    exit 1
+	echo "Please setup the configuration file first!"
+	exit 1
 elif [[ -z ${backup_root} ]] || [[ -z ${folders_to_backup} ]] || [[ -z ${mysqlbackup} ]]; then
-    echo "Invalid configuration file!"
-    exit 1
+	echo "Invalid configuration file!"
+	exit 1
 elif [[ ${mysqlbackup} == "yes" ]]; then
-    if [[ -z ${mysqluser} ]] || [[ -z ${mysqlpass} ]]; then
+	if [[ -z ${mysqluser} ]] || [[ -z ${mysqlpass} ]]; then
 	echo "You're set the MySQL backup to yes, but you dont set the user/password correctly."
 	exit 1
-    fi
+	fi
 fi
 
 if [ ! -d ${backup_root} ]; then
-    echo "Backup root folder doesn't exsist!"
-    exit 1
+	echo "Backup root folder doesn't exsist!"
+	exit 1
 else
-    touch ${backup_root}/testfile 2>/dev/null && rm -f ${backup_root}/testfile || backuprw="no"
+	touch ${backup_root}/testfile 2>/dev/null && rm -f ${backup_root}/testfile || backuprw="no"
 fi
 
 if [[ ${backuprw} == "no" ]]; then
-    echo "Backup root directory ($backup_root) is not writeable!"
-    exit 1
+	echo "Backup root directory ($backup_root) is not writeable!"
+	exit 1
 fi
 
 #################################
@@ -71,25 +74,33 @@ day=$(date +'%-a')
 month=$(date +'%-b')
 
 if [[ ${dayofweek} == "1" ]] && [[ ${dayofmonth} -lt "8" ]]; then
-    firstmon="1"
+	firstmon="1"
 else
-    firstmon="0"
+	firstmon="0"
+fi
+
+diskfree=$(df -k ${backup_root} | tail -1 | awk '{print $4}')
+if [[ ! -z ${backup_minfree} ]]; then
+	if [[ ${diskfree} -lt ${backup_minfree} ]]; then
+		echo "Not enough free space on backup target!"
+		exit 1
+	fi
 fi
 
 dailyInc()
 {
 for bck in ${folders_to_backup}; do
-    echo -n "Making daily incremental backup from folder ${bck} with date ${date} . . ."
-    find ${bck} -newermt $(date +%Y-%m-%d -d '1 day ago') -type f -print | nice -n 19 ionice -c3 tar zcvf ${backup_root}/$(basename ${bck})-[${date}]-[Daily-Inc-${day}].tgz -T - > /dev/null 2>&1
-    echo "Backup completed"
+	echo -n "Making daily incremental backup from folder ${bck} with date ${date} . . ."
+	find ${bck} -newermt $(date +%Y-%m-%d -d '1 day ago') -type f -print | nice -n 19 ionice -c3 tar zcvf ${backup_root}/$(basename ${bck})-[${date}]-[Daily-Inc-${day}].tgz -T - > /dev/null 2>&1
+	echo "Backup completed"
 done
 
 for bck in ${folders_to_backup_subdir}; do
-    for subdir in $(ls ${folders_to_backup_subdir}); do
+	for subdir in $(ls ${folders_to_backup_subdir}); do
 		echo -n "Making daily incremental backup from folder ${folders_to_backup_subdir}/${subdir} with date ${date} . . ."
 		find ${folders_to_backup_subdir}/${subdir}/* -newermt $(date +%Y-%m-%d -d '1 day ago') -type f -print | nice -n 19 ionice -c3 tar zcvf ${backup_root}/${subdir}-[${date}]-[Daily-Inc-${day}].tgz -T - > /dev/null 2>&1
 		echo "Backup completed"
-    done
+	done
 done
 }
 
